### ISSUE TITLE
关于激活码无效问题。

### ISSUE THREAD

**Issue by Chrike** [NotoChen/Jetbrains-Help#4]
你好，我正在使用您的项目，并在控制台看到了激活码。然而，我发现这个激活码无法使用，我不清楚原因。我从其他地方获取的激活码却可以成功激活，前提是我配置了别人的vmoptions，我改javaagent改为从运行结果下载的路径，别人的激活码也无效了。

我注意到，可以激活的激活码比我自己生成的要长得多。我想了解一下，这个激活码是如何生成的？它与IDEA的版本有关吗？同时，我也下载java21。

此外，我在配置vmoptions时，将jar包更换为我运行结果下载的ja-netfilter.jar，发现该本可以激活码也无法激活。但是，当我将-javaagent:D更改为别人的jar包时，我可以使用别人的激活码。而且好像别人的jar包还多了一些东西。
[Uploading idea.zip…]()

别人的配置vmoptions：--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED
-javaagent:D:/idea/idea.jar

比如插件.DataGraph

使用别人的激活码是（加上别人的配置vmoptions可以激活）
[新建 文本文档 (2).txt](https://github.com/NotoChen/Jetbrains-Help/files/15040292/2.txt)

而我自己生成的激活码是（不管是自己运行结果下载的，还是别人的配置vmoptions都不能激活）

[新建 文本文档 (2).txt](https://github.com/NotoChen/Jetbrains-Help/files/15040310/2.txt)

期待您的回复。

**Comment by iamananba** [comment]
+1
