### ISSUE TITLE
build 报错，提示缺少环境

### ISSUE THREAD

**Issue by nn200433** [NotoChen/Jetbrains-Help#6]
```
Sending build context to Docker daemon  1.114MB
Step 1/11 : FROM maven:3-ibm-semeru-21-jammy as build
 ---> c3fbfb491d6a
Step 2/11 : WORKDIR /app
 ---> Using cache
 ---> 7d40c1419543
Step 3/11 : COPY . .
 ---> Using cache
 ---> 659231d00675
Step 4/11 : RUN mvn clean package
 ---> Running in 74e42a9327db
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.
The command '/bin/sh -c mvn clean package' returned a non-zero code: 1
[root@VM-12-7-centos Jetbrains-Help]# 
```

**Comment by watchingfun** [comment]
**The JAVA_HOME environment variable is not defined correctly**

[答案](https://www.lmgt.com/?q=The+JAVA_HOME+environment+variable+is+not+defined+correctly)

**Comment by nn200433** [comment]
> **The JAVA_HOME environment variable is not defined correctly**
> 
> [答案](https://www.lmgt.com/?q=The+JAVA_HOME+environment+variable+is+not+defined+correctly)

那是提供的docker build会这样，说明dockerfile有问题。我直接本地打包做镜像了。

还有需要你教我去搜索？你怕是没长大吧。

**Comment by watchingfun** [comment]
> > **The JAVA_HOME environment variable is not defined correctly**
> > [答案](https://www.lmgt.com/?q=The+JAVA_HOME+environment+variable+is+not+defined+correctly)
> 
> 那是提供的docker build会这样，说明dockerfile有问题。我直接本地打包做镜像了。
> 
> 还有需要你教我去搜索？你怕是没长大吧。

我很抱歉，我没仔细看，对docker也不太熟悉，对你的冒犯抱歉；

根据你提交issue的日期是5月9号，我看了下最新的dockerfile使用的jdk镜像，是有配置JAVA_HOME环境变量的，而且我git clone仓库到wsl2上，是可以正常docker build和运行的

再次对你的冒犯抱歉；
